version: '3.8'

services:
  postgres:
    image: postgres
    container_name: segunda_api_fastapi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: segunda_api_fastapi
    volumes:
    #C:\xampp\htdocs\fastApi\docker\volumes trocar para seu diretorio
      - C:\xampp\htdocs\fastApi\docker\volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  meu_volume_postgres:
